default:

  # settings for MISRIS (central budget starting from 2015)
  sp_months_central_new: 12 # which month's data to download
  sp_years_central_new: !expr 2015:2021 # which years to download
  sp_central_arrowdir_new: "data-processed/sp-central-new-arr"

  sp_nastroj_ids_1420_ops: ["102", "103", "104", "105", "106", "107", "108", "109"]
  sp_nastroj_ids_1420_prv: ["130", "187"]

  sp_nastroj_ids_0713_ops: ["30", "31", "33", "36", "37", "38", "39", "40", "51", "52", "53", "54"]
  sp_nastroj_ids_0713_prv: ["27", "87"]

  # settings for FINU (central budget 2010-2014)
  sp_years_central_old: !expr 2010:2014
  sp_months_central_old: 12
  sp_central_arrowdir_old: "data-processed/sp-central-old-arr"

  # settings for FINM (local budget 2010-2014)
  sp_years_local: !expr 2010:2020
  sp_months_local: 12
  sp_local_arrowdir: "data-processed/sp-local-arr"
  sp_local_grants_arrowdir: "data-processed/sp-local-grants-arr"

  # settings for FINSF (state funds 2015-)
  sp_months_sf: 12
  sp_sf_arrowdir: "data-processed/sp-sf-arr"

  # URL for getting project data
  ef_pubxls_url: "https://dotaceeu.cz/getmedia/6297d56b-0b57-418d-ad25-dd16bd687479/2021_06-Seznam-operaci-_-List-of-operations.xls.aspx?ext=.xls"

  # sestavy from MS
  sest_dir: "data-input/sestavy 20210528"
  sest_xlsx_prj: "E001 Identifikace projektu.xlsx"
  sest_xlsx_fin: "E003 Finance celkem.xlsx"
  sest_xlsx_zop: "E004 Žádosti o platbu.xlsx"
  sest_xlsx_obl: "E005 Kategorizace_oblast.xlsx"

  # PRV data-input

  prv_data_path: "data-input/prv/PRV 2014-20 k XII. 2020.XLSX"

  # Quest/Hermin categorisations
  mc_xlsx_q: "data-input/kategorizace/kategorie_questNEW-2.xlsx"
  mc_xlsx_h: "data-input/kategorizace/AIS_desagregace_rHERMIN.xlsx"
  mc_xlsx_prv: "data-input/kategorizace/Navrh - KATEGORIZACE - Operace PRV + priority.xlsx"

  # Arrow directory of cleaned up geolocation data for projects
  ef_obce_arrowdir: "data-input/esif-projekty-obce"

  # Excel file with hierarchy of all objectives and categories
  hier_excel_path: "data-input/matice/Hierarchie_uprava_CSR_NPR-O27-uprava_20210125.xlsx"
  hier_excel_sheet: SC

  # IDs
  czso_pop_table_id: "130149"

  # export location

  export_dir: "data-export"
  export_sum_xlsx: "esif_sr.xlsx"
  export_sum_csv: "esif_sr.csv"
  export_sum_pq: "esif_sr.parquet"
  export_detail_pq: "esif_sr_detail.parquet"

  export_cdbk: "codebook.yaml"

  repo_remote: "https://github.com/petrbouchal/esifinancuji"
  docs_url: "https://esifinancuji.petrbouchal.xyz"

  # data from 2017 study
  first_report_xlsx: "data-input/adic2017/vydaje_dataset.xlsx"
